
--
-- TOC entry 224 (class 1259 OID 16511)
-- Name: Examinations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Examinations" (
    "Id" bigint NOT NULL,
    "PatientId" bigint NOT NULL,
    "DateOfExam" timestamp with time zone NOT NULL,
    "ExamType" integer NOT NULL,
    "PicturePath" text
);


ALTER TABLE public."Examinations" OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16510)
-- Name: Examinations_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Examinations" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Examinations_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16524)
-- Name: MedDocumentations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MedDocumentations" (
    "Id" bigint NOT NULL,
    "Diagnosis" text NOT NULL,
    "PatientId" bigint NOT NULL,
    "StartIllness" timestamp with time zone NOT NULL,
    "EndIllness" timestamp with time zone
);


ALTER TABLE public."MedDocumentations" OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16523)
-- Name: MedDocumentations_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."MedDocumentations" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."MedDocumentations_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16503)
-- Name: Patients; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Patients" (
    "Id" bigint NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "Oib" text NOT NULL,
    "DateOfBirth" timestamp with time zone NOT NULL,
    "Gender" integer NOT NULL,
    "NumberOfPatient" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public."Patients" OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16502)
-- Name: Patients_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Patients" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Patients_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16537)
-- Name: Prescriptions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Prescriptions" (
    "Id" bigint NOT NULL,
    "PatientId" bigint NOT NULL,
    "Medication" text NOT NULL,
    "Dose" text NOT NULL,
    "Frequency" text NOT NULL,
    "Duration" text NOT NULL
);


ALTER TABLE public."Prescriptions" OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16536)
-- Name: Prescriptions_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Prescriptions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Prescriptions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16497)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 3224 (class 2606 OID 16727)
-- Name: Examinations PK_Examinations; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Examinations"
    ADD CONSTRAINT "PK_Examinations" PRIMARY KEY ("Id");


--
-- TOC entry 3227 (class 2606 OID 16724)
-- Name: MedDocumentations PK_MedDocumentations; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MedDocumentations"
    ADD CONSTRAINT "PK_MedDocumentations" PRIMARY KEY ("Id");


--
-- TOC entry 3221 (class 2606 OID 16555)
-- Name: Patients PK_Patients; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Patients"
    ADD CONSTRAINT "PK_Patients" PRIMARY KEY ("Id");


--
-- TOC entry 3230 (class 2606 OID 16721)
-- Name: Prescriptions PK_Prescriptions; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Prescriptions"
    ADD CONSTRAINT "PK_Prescriptions" PRIMARY KEY ("Id");


--
-- TOC entry 3219 (class 2606 OID 16501)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3222 (class 1259 OID 16730)
-- Name: IX_Examinations_PatientId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Examinations_PatientId" ON public."Examinations" USING btree ("PatientId");


--
-- TOC entry 3225 (class 1259 OID 16729)
-- Name: IX_MedDocumentations_PatientId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_MedDocumentations_PatientId" ON public."MedDocumentations" USING btree ("PatientId");


--
-- TOC entry 3228 (class 1259 OID 16728)
-- Name: IX_Prescriptions_PatientId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Prescriptions_PatientId" ON public."Prescriptions" USING btree ("PatientId");


--
-- TOC entry 3231 (class 2606 OID 16731)
-- Name: Examinations FK_Examinations_Patients_PatientId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Examinations"
    ADD CONSTRAINT "FK_Examinations_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES public."Patients"("Id") ON DELETE CASCADE;


--
-- TOC entry 3232 (class 2606 OID 16736)
-- Name: MedDocumentations FK_MedDocumentations_Patients_PatientId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MedDocumentations"
    ADD CONSTRAINT "FK_MedDocumentations_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES public."Patients"("Id") ON DELETE CASCADE;


--
-- TOC entry 3233 (class 2606 OID 16741)
-- Name: Prescriptions FK_Prescriptions_Patients_PatientId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Prescriptions"
    ADD CONSTRAINT "FK_Prescriptions_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES public."Patients"("Id") ON DELETE CASCADE;


-- Completed on 2025-01-30 18:46:24

--
-- PostgreSQL database dump complete
--

